### ISSUE TITLE
Relating Arbiter to ADR Documentation

### ISSUE THREAD

**Issue by dolfelt** [arbiterphp/Arbiter.Arbiter#1]
@pmjones How does this library work according the ADR spec?

https://github.com/pmjones/adr#comparison-to-mvc-model-view-controller

I understand how it should work from and implementation standpoint, but after reading through the documentation again, it appears that `Actions` are to be viewed like `Controllers` in MVC, but that doesn't make much sense to me, since the `Action` and `ActionHandler` in this library act more like a data object and transport between Input, Domain and Responder, not something with specific logic in it.

Again, I think the way this library works is fantastic, but I'm just trying to understand it in relation to the original documentation. Your insights would be greatly appreciated. Thanks!

cc: @shadowhand @ameech

**Comment by shadowhand** [comment]
I think this is just a common misunderstanding of what Controllers are supposed to do. A controller is not supposed to contain domain logic, it is supposed to marshall request data and collaborators to do the business logic, which should exist in Models. In MVC, we often hear about "thin controllers, fat models" and this is exactly what is implied by that statement.

**Comment by pmjones** [comment]
@shadowhand has it exactly right. To expand on that a bit: When I first started writing in the ADR pattern, my actions ended up all looking exactly the same, with only minor variations in how to the input was marshaled. Standardizing the action behavior was a natural next step.

**Comment by ameech** [comment]
When I read the spec I interpreted it as an action is just a traditional MVC controller action, which just received the input, passed the data to the domain and then returns the response. More of an interface to the system, that HTTP or CLI would work with.

Here is a repo I put together with my interpretation: https://github.com/ameech/shifty

**Comment by pmjones** [comment]
> received the input, passed the data to the domain and then returns the response.

As long as the response-building work is handed off to a responder, then yes, the action can return the response directly.

> More of an interface to the system, that HTTP or CLI would work with.

Yes, exactly.

> Here is a repo I put together with my interpretation: https://github.com/ameech/shifty

I would argue that most of the work in Action/GetList.php should actually be in the Domain. The Action should collect the input and hand it to the Domain, and get back a result (in this case a Payload) from the Domain. That result would then be handed to a Responder, which would build the response. Each Actions really should be dead stupid simple.

**Comment by ameech** [comment]
That action is messy with fractal in there, but the only portion of it that interacts with the domain is: `$this->shifts->findAll()`. Do you think there should be another level of abstraction there? Seems unnecessary.

**Comment by pmjones** [comment]
If I recall correctly, Fractal is what transforms the result data into a presentable form for output. If that's correct, then Fractal should be in the Responder portion, not in the Action.  All the action should do is take the request object and get the input data from it, pass that to a domain call, and pass the domain result to the responder. Small though it is, it looks like you are combining concerns in that short bit of code.

**Comment by ameech** [comment]
Should've been more clear, Fractal should definitely not be in there, I just had it in there for a quick poc.

**Comment by pmjones** [comment]
/me nods

For example, you might try splitting out the Domain callable to this:

```
public function __invoke()
{
    $payload = new Payload();
    $payload->setStatus(Payload::FOUND);
    $payload->setOutput([
        'shifts' => $this->shifts->findAll();
    ]);
    return $payload;
}
```

And a Responder callable to this:

```
public function __invoke($request, $response, $payload)
{
    $data = $payload->getOutput('shifts');
    $coll = new Collection($data, new Shift);
    $array = (new Manager)->createData($coll)->toArray();
    $response->getBody()->write(json_encode($array));
}
```

I am not familiar with Fractal so I might have missed something critical.

Then your action merely calls the Domain callable, and passes the Payload to the Responder callable.

You see where I'm coming from?

**Comment by ameech** [comment]
Yep, I do! Thanks for the explanation.

**Comment by dolfelt** [comment]
@pmjones @shadowhand So we are saying the most people do MVC wrong, with most logic being in the Controller (including input parsing and http handling), and that if they did it correctly, it would better mimic the MVC to ADR comparison?

From a common use standpoint, I see Controller action being mostly Domain, Model being a DataMapper/Entity of sorts, and the View being the Responder. The Action in ADR would be a new marshaller between the Router, Controller and View.

```
Action            <--> (new marshaller)
Domain            <--> Controller
Responder         <--> View
DataMapper/Entity <--> Model
```

Maybe this isn't the ideal way to describe it, but it's what makes sense in my head based on how 90%+ of people use the MVC spec (all of who may be wrong :wink:).

**Comment by shadowhand** [comment]
Yes, most people do ~~MVC~~ programming wrong because there is no perfect answer. From what I understand of ADR, one of the reasons for defining a new pattern was to help correct the baggage of arguing about where domain logic does in MVC. So I don't really think it is terribly useful to make arbitrary arrows pointing at things to denote similarity. :sunglasses:

**Comment by shadowhand** [comment]
(Oops I hit the button too fast... I was going to add:)

I think one of the major issues that people need to overcome mentally is when they hear "MVC" or "ADR" they think "okay we have 3 things" but in reality, the "domain" (or "model") portion of the triad represents a **gateway** into the rest of your code. Again, one of the big failings of nearly every framework is that they don't clearly show us how to build stuff inside the domain/model. They give us a bunch of tools that deal with the outer layers, and very little to help us organize the inner (domain) layers. (Arguably, this is not the job of a framework at all, because domain organization is specific to the business.)

So what the hell does that mean? It means that we have to stop thinking of domain as the place that "everything else" happens. In the same way we think about splitting the concerns of action and responder and domain, we need to further split the concerns of the domain using other design patterns. This is where the world of Command Bus and State Machine and _most_ design patterns actually exist.

It should also be noted that it is _extremely_ difficult to give good examples of how a domain should be organized. The stuff that happens in the domain is the hardest part of programming. It is where we run into the issues around naming things. It is where we trip ourselves up trying to determine how to write testable code. It is where the most difficult dependency inversion problems lie.

I say all of this because I feel like this conversation is losing sight of the forest for all the trees. ADR is not an answer to everything it just gives us a better (and more strict) way to provide a gateway to the domain. How we organize the domain is our job, not Paul's.

**Comment by dolfelt** [comment]
I agree with everything @shadowhand says. I was just trying to understand the comparisons. In my opinion they just didn't make sense. ADR makes sense to me, as to most other aspects of the Domain layer. This was just about the comparison, and I only brought it up because it was there. It made it all confusing to think about because I don't think the comparison is adequate.

Beyond that, I think ADR is a great design pattern and I agree with the way it's structured.

**Comment by elazar** [comment]
[Good related presentation on MVC and related misnomers](https://www.youtube.com/watch?v=UV4YUCkKrGc#t=1m22s).

Re: ADR vs MVC, I agree with @shadowhand about it representing a gateway into the application logic. What Radar/Relay/Arbiter accomplish is providing a sufficient abstraction layer for the access point protocol (e.g. HTTP, CLI, etc). The Domain should be protocol-independent/agnostic, the Responder returns the payload in a way that is suitable for that protocol.

**Comment by pmjones** [comment]
> the "domain" (or "model") portion of the triad represents a gateway into the rest of your code.

:+1:

**Comment by pmjones** [comment]
@elazar That's a good talk; the ADR paper has a link to an earlier version of that talk (http://vimeo.com/40968850).

If you guys can bear the terrible audio, I have a talk on the transition from MVC to ADR at https://vimeo.com/106771285 -- I should link that in the ADR paper as well.

**Comment by pmjones** [comment]
Closing this, subject to further need-to-discuss, as the issue seems to have fulfilled its purpose.
