### ISSUE TITLE
Order of parameters for Action?

### ISSUE THREAD

**Issue by shadowhand** [arbiterphp/Arbiter.Arbiter#3]
The current Action signature is:

``` php
new Action($input, $domain, $responder);
```

I'm thinking that this might not be the most optimal order, because it does not allow the input to have a default value. As per your comment on pmjones/adr#35:

> For my part, having worked with ADR for a while, it turns out that every Action ends up doing exactly the same thing: marshal input, call the domain with that input to get a result, pass that result to the responder. As such, the Action portion can be completely extracted, and all you need to do is specify an input callable, a domain callable, and a responder callable; that information can be specified very easily via the routing system. That's what led first to Radar, and then (via Spark) to Arbiter.

The thing that strikes me as always unique in every ADR triad is the domain part. In many scenarios, you can get away with having an input that [takes everything](https://github.com/radarphp/Radar.Adr/blob/9e8fe698c6ebc62d859ebad3b8ea035febd9c019/src/Input.php) and a responder that is [content negotiated](https://github.com/sparkphp/spark/blob/master/src/Responder/FormattedResponder.php).

The second most likely thing to need to be customized would be the responder. Since in some applications you may have certain things that cannot be rendered as JSON but only as HTML. In those scenarios, it would be necessary to have an explicit responder, rather than one that is content negotiated.

Based on these observations, I think it might be more realistic to have:

``` php
new Action($domain, $responder, $input);
```

By changing the order of the parameters, we could have an extended action like:

``` php
namespace Spark;

use Arbiter\Action as BaseAction;
use Spark\Input;
use Spark\Responder\FormattedResponder;

class Action extends BaseAction
{
    public function __construct(
        $domain,
        $responder = FormattedResponder::class,
        $input = Input::class
    ) {
        return parent::construct($domain, $responder, $input);
    }
}
```

I realize that absolutely nothing prevents us from doing this now, I just thought it was worth mentioning for future consideration.

**Comment by pmjones** [comment]
I think this has merit. Let me get back to you on it, as I have other demands on my time right now.

**Comment by pmjones** [comment]
As a side note that makes the signature "DRI" (heh).

**Comment by pmjones** [comment]
I've had this on my mind since you reported it, and have been working through it off-and-on. The difference is one of "conceptual" order (input goes to domain, domain output goes to responder) versus "standardizing" order (the domain is the least-standard thing across all actions, responders are the next-least standard, and input could well be standardized across all domain calls).

After having changed things around in experimental branches, though, I'm realizing that there's another order: "optionality." As far as the ActionHandler is concerned, the least-optional thing is the Responder. It _has_ to be there, otherwise there's no result from the action at all. The next-least-optional thing is the Domain, since it might not need any input at all; and finally there is the Input. That implies an order of `($responder, $domain, $input)`, which had not occurred to me before.

I have not settled on anything yet, just wanted to let you know I have not forgotten this.

**Comment by shadowhand** [comment]
Standard order is most useful to me, and I would assume others. We're using it like [this](https://github.com/equip/framework/blob/41bd201996c906988e9bbbce09be178003353eec/src/Action.php).

**Comment by pmjones** [comment]
/me nods

After working through this, it seems to me that the best thing is to leave the arguments in "conceptual" order; I find it difficult to write the explanatory documentation for it any other way than that order.

With that order, it seems reasonable to have an Action factory class or factory method provide the default values, instead of extending the Action class and providing default values in the extended class and constructor. (Radar uses the factory approach already, though the defaults are provided as part of the Route, and the Action instance is created much later in dispatch process; cf. `Radar\Adr\Route` and `Radar\Adr\HandlerRoutingHandler::routeRequest()`).

What that would mean for Equip, if you cared to follow that path, might be for the `Directory::action()` to go from ...

``` php
    $action = new Action($domainOrAction);
```

... to:

``` php
    $action = new Action(
        'Equip\Input',
        $domainOrAction
        'Equip\Responder\ChainedResponder'
    );
```

Of course, that's only reasonable if you expect those to be the only Input and Responder classes; otherwise you'd need a way to specify alternate classes, but I think that's true under the current implementation as well.

That means you can use the standard Arbiter Action class, without needing an extended class.

Or you could leave things as they are with the extended class; as you say, overriding the constructor works perfectly well for your purposes.

FWIW, one thing this examination has revealed to me is that the $responder value might be un-callable, and so I need to add checking on that in Arbiter. Thanks for that in any case.
